name: Build workflow
on:
    workflow_call:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: npm run build --if-present
            - run: npm run package
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                  path: hyread_chrome_ext.zip
