name: Upload artifact workflow
on:
    workflow_call:
jobs:
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                  path: hyread_chrome_ext.zip
