name: CI file
run-name: ${{ github.actor }} is running CI
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup nodejs with version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: setup ci
        run: npm ci --legacy-peer-deps
      - name: unit testing
        run: npm test
      - name: build chrome extension
        run: npm run build --if-present
