name: CI file
run-name: ${{ github.actor }} is running CI
on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'
jobs:
    prepare:
        uses: ./.github/workflows/prepare.yaml
        with:
            commit_ref: ${{ github.ref }}
    unittest:
        needs: prepare
        uses: ./.github/workflows/unittest.yaml
    build:
        needs: unittest
        uses: ./.github/workflows/build.yaml 