name: CI file
run-name: ${{ github.actor }} is running CI
on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'
      - 'main'
jobs:
    unittest:
        uses: ./.github/workflows/unittest.yaml
        with:
            commit_ref: ${{ github.ref }}