name: tag release
run-name: ${{ github.actor }} is doing tag release
on:
  push:
    tags:
      - v**
jobs:
    prepare:
        uses: ./.github/workflows/prepare.yaml
        with:
            commit_ref: ${{ github.ref }}
    unittest:
        needs: prepare
        uses: ./.github/workflows/unittest.yaml
    build:
        needs: unittest
        uses: ./.github/workflows/build.yaml 
    artifact:
        needs: build
        uses: ./.github/workflows/artifact.yaml